MONGO_URI = ""
DATABASE = ""
MONTH_MASK = { 1 :"Janeiro", 2 :"Fevereiro", 3 :"Março", 4 :"Abril", 5 :"Maio", 6 :"Junho", 7 :"Julho", 8 :"Agosto", 9 :"Setembro", 10:"Outubro", 11:"Novembro", 12:"Dezembro" }
YEARS = [ 2023, 2024 ]
ICON_PAGE_HOME = ":material/home:"
ICON_PAGE_CONSOLIDACAO = ":material/add_chart:"
ICON_PAGE_ENVIO_METRICAS = ":material/cloud_upload:"
PATH_LOGO = "img/ecg_40dp_999999.svg"
PATH_HOME_IMG = "img/planet_100dp_999999.svg"
